/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainRouteImport } from './routes/train'
import { Route as PetRouteImport } from './routes/pet'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatUserIdRouteImport } from './routes/chat.$userId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUserIdRoute = ChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pet': typeof PetRoute
  '/train': typeof TrainRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$userId': typeof ChatUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pet': typeof PetRoute
  '/train': typeof TrainRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$userId': typeof ChatUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pet': typeof PetRoute
  '/train': typeof TrainRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$userId': typeof ChatUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/auth'
    | '/friends'
    | '/leaderboards'
    | '/pet'
    | '/train'
    | '/auth/callback'
    | '/chat/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/auth'
    | '/friends'
    | '/leaderboards'
    | '/pet'
    | '/train'
    | '/auth/callback'
    | '/chat/$userId'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/auth'
    | '/friends'
    | '/leaderboards'
    | '/pet'
    | '/train'
    | '/auth/callback'
    | '/chat/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  AuthRoute: typeof AuthRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PetRoute: typeof PetRoute
  TrainRoute: typeof TrainRoute
  ChatUserIdRoute: typeof ChatUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$userId': {
      id: '/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof ChatUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  AuthRoute: AuthRouteWithChildren,
  FriendsRoute: FriendsRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PetRoute: PetRoute,
  TrainRoute: TrainRoute,
  ChatUserIdRoute: ChatUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
